// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	Recipeid int
	Category string
}

type Image struct {
	Imageid   int
	Recipeid  sql.NullInt32
	Stepid    sql.NullInt32
	Image     []byte
	Timestamp time.Time
}

type Ingredient struct {
	Ingredientid    int
	Recipeid        int
	Ingredient      string
	Unit            sql.NullString
	Amount          sql.NullFloat64
	Ingredientgroup sql.NullString
}

type Recipe struct {
	Recipeid          int
	Title             string
	Description       sql.NullString
	Cookingtime       sql.NullInt32
	Coverimage        sql.NullInt32
	Portions          sql.NullFloat64
	Userid            sql.NullInt32
	Clicks            int
	Creationtimestamp time.Time
}

type Recipestep struct {
	Stepid   int
	Recipeid int
	Orderid  int
	Step     string
}

type User struct {
	Userid   int
	Username string
	Password string
	Isadmin  bool
	Disabled sql.NullBool
}
