// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const getCategoriesByRecipe = `-- name: GetCategoriesByRecipe :many
SELECT Category FROM Categories WHERE RecipeID = ?
`

func (q *Queries) GetCategoriesByRecipe(ctx context.Context, recipeid int) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByRecipe, recipeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGalleryImagesByRecipe = `-- name: GetGalleryImagesByRecipe :many
SELECT i.ImageID FROM Images i, Recipes r WHERE i.RecipeID = ? AND r.RecipeID = i.RecipeID AND i.StepID IS NULL AND i.ImageID != r.CoverImage
`

func (q *Queries) GetGalleryImagesByRecipe(ctx context.Context, recipeid sql.NullInt32) ([]int, error) {
	rows, err := q.db.QueryContext(ctx, getGalleryImagesByRecipe, recipeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var imageid int
		if err := rows.Scan(&imageid); err != nil {
			return nil, err
		}
		items = append(items, imageid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByRecipeStep = `-- name: GetImagesByRecipeStep :many
SELECT ImageID FROM Images WHERE StepID = ?
`

func (q *Queries) GetImagesByRecipeStep(ctx context.Context, stepid sql.NullInt32) ([]int, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByRecipeStep, stepid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var imageid int
		if err := rows.Scan(&imageid); err != nil {
			return nil, err
		}
		items = append(items, imageid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIngredientsByRecipe = `-- name: GetIngredientsByRecipe :many
SELECT Ingredient, Unit, Amount, IngredientGroup FROM Ingredients WHERE RecipeID = ?
`

type GetIngredientsByRecipeRow struct {
	Ingredient      string
	Unit            sql.NullString
	Amount          sql.NullFloat64
	Ingredientgroup sql.NullString
}

func (q *Queries) GetIngredientsByRecipe(ctx context.Context, recipeid int) ([]GetIngredientsByRecipeRow, error) {
	rows, err := q.db.QueryContext(ctx, getIngredientsByRecipe, recipeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientsByRecipeRow
	for rows.Next() {
		var i GetIngredientsByRecipeRow
		if err := rows.Scan(
			&i.Ingredient,
			&i.Unit,
			&i.Amount,
			&i.Ingredientgroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipe = `-- name: GetRecipe :one
SELECT r.RecipeID, r.Title, r.Description, r.CookingTime, r.CoverImage, r.Portions, u.Username, u.UserID, r.Clicks FROM Recipes r, Users u WHERE r.RecipeID = ? AND r.UserID = u.UserID LIMIT 1
`

type GetRecipeRow struct {
	Recipeid    int
	Title       string
	Description sql.NullString
	Cookingtime sql.NullInt32
	Coverimage  sql.NullInt32
	Portions    sql.NullFloat64
	Username    string
	Userid      int
	Clicks      int
}

func (q *Queries) GetRecipe(ctx context.Context, recipeid int) (GetRecipeRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, recipeid)
	var i GetRecipeRow
	err := row.Scan(
		&i.Recipeid,
		&i.Title,
		&i.Description,
		&i.Cookingtime,
		&i.Coverimage,
		&i.Portions,
		&i.Username,
		&i.Userid,
		&i.Clicks,
	)
	return i, err
}

const getRecipeStepsByRecipe = `-- name: GetRecipeStepsByRecipe :many
SELECT StepID, OrderID, Step FROM RecipeSteps WHERE RecipeID = ?
`

type GetRecipeStepsByRecipeRow struct {
	Stepid  int
	Orderid int
	Step    string
}

func (q *Queries) GetRecipeStepsByRecipe(ctx context.Context, recipeid int) ([]GetRecipeStepsByRecipeRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipeStepsByRecipe, recipeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeStepsByRecipeRow
	for rows.Next() {
		var i GetRecipeStepsByRecipeRow
		if err := rows.Scan(&i.Stepid, &i.Orderid, &i.Step); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClicks = `-- name: UpdateClicks :exec
UPDATE Recipes SET Clicks = Clicks + 1 WHERE RecipeID = ?
`

func (q *Queries) UpdateClicks(ctx context.Context, recipeid int) error {
	_, err := q.db.ExecContext(ctx, updateClicks, recipeid)
	return err
}
