CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    IsAdmin TINYINT(1) NOT NULL,
    Disabled TINYINT(1) DEFAULT NULL
);

CREATE TABLE Recipes (
    RecipeID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Description VARCHAR(500) DEFAULT NULL,
    CookingTime INT DEFAULT NULL,
    CoverImage INT DEFAULT NULL,
    Portions FLOAT DEFAULT NULL,
    UserID INT DEFAULT NULL,
    Clicks INT NOT NULL DEFAULT 0,
    CreationTimeStamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE SET NULL,
    INDEX (CoverImage)
);

CREATE TABLE RecipeSteps (
    StepID INT AUTO_INCREMENT PRIMARY KEY,
    RecipeID INT NOT NULL,
    OrderID INT NOT NULL,
    Step LONGTEXT NOT NULL,
    FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID) ON DELETE CASCADE
);

CREATE TABLE Images (
    ImageID INT AUTO_INCREMENT PRIMARY KEY,
    RecipeID INT DEFAULT NULL,
    StepID INT DEFAULT NULL,
    Image MEDIUMBLOB NOT NULL,
    TimeStamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID) ON DELETE SET NULL,
    FOREIGN KEY (StepID) REFERENCES RecipeSteps(StepID) ON DELETE SET NULL
);

CREATE TABLE Ingredients (
    IngredientID INT AUTO_INCREMENT PRIMARY KEY,
    RecipeID INT NOT NULL,
    Ingredient VARCHAR(100) NOT NULL,
    Unit VARCHAR(10) DEFAULT NULL,
    Amount FLOAT DEFAULT NULL,
    IngredientGroup VARCHAR(50) DEFAULT NULL,
    FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID) ON DELETE CASCADE
);

CREATE TABLE Categories (
    RecipeID INT NOT NULL,
    Category VARCHAR(100) NOT NULL,
    PRIMARY KEY (RecipeID, Category),
    FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID) ON DELETE CASCADE
);

ALTER TABLE Recipes ADD CONSTRAINT fk_recipes_coverimage FOREIGN KEY (CoverImage) REFERENCES Images(ImageID) ON DELETE SET NULL;