name: 🎉 Deploy frontend
run-name: Deploy Frontend
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: 🔨 Build Project
        run: |
          cd frontend
          npm ci
          npm run build
      - name: 📂 Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: frontend/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download production build artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
      - name: 🚀 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.YODA }}
          server: ${{ secrets.CORUSCANT }}
          ssh_private_key: ${{ secrets.YODAS_SPELL }}
          local_path: "./"
          remote_path: "/homw/www/flottekueche.de"
